/*   Copyright (C) 2013-2014 Computer Sciences Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License. */

/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ezbake.services.centralPurge.thrift;

import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ApplicationPurgeState implements org.apache.thrift.TBase<ApplicationPurgeState, ApplicationPurgeState._Fields>, java.io.Serializable, Cloneable, Comparable<ApplicationPurgeState> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ApplicationPurgeState");

  private static final org.apache.thrift.protocol.TField SERVICE_PURGESTATES_FIELD_DESC = new org.apache.thrift.protocol.TField("servicePurgestates", org.apache.thrift.protocol.TType.MAP, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new ApplicationPurgeStateStandardSchemeFactory());
    schemes.put(TupleScheme.class, new ApplicationPurgeStateTupleSchemeFactory());
  }

  public Map<String,ServicePurgeState> servicePurgestates; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    SERVICE_PURGESTATES((short)1, "servicePurgestates");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // SERVICE_PURGESTATES
          return SERVICE_PURGESTATES;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.SERVICE_PURGESTATES, new org.apache.thrift.meta_data.FieldMetaData("servicePurgestates", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ServicePurgeState.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ApplicationPurgeState.class, metaDataMap);
  }

  public ApplicationPurgeState() {
  }

  public ApplicationPurgeState(
    Map<String,ServicePurgeState> servicePurgestates)
  {
    this();
    this.servicePurgestates = servicePurgestates;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ApplicationPurgeState(ApplicationPurgeState other) {
    if (other.isSetServicePurgestates()) {
      Map<String,ServicePurgeState> __this__servicePurgestates = new HashMap<String,ServicePurgeState>(other.servicePurgestates.size());
      for (Map.Entry<String, ServicePurgeState> other_element : other.servicePurgestates.entrySet()) {

        String other_element_key = other_element.getKey();
        ServicePurgeState other_element_value = other_element.getValue();

        String __this__servicePurgestates_copy_key = other_element_key;

        ServicePurgeState __this__servicePurgestates_copy_value = new ServicePurgeState(other_element_value);

        __this__servicePurgestates.put(__this__servicePurgestates_copy_key, __this__servicePurgestates_copy_value);
      }
      this.servicePurgestates = __this__servicePurgestates;
    }
  }

  public ApplicationPurgeState deepCopy() {
    return new ApplicationPurgeState(this);
  }

  @Override
  public void clear() {
    this.servicePurgestates = null;
  }

  public int getServicePurgestatesSize() {
    return (this.servicePurgestates == null) ? 0 : this.servicePurgestates.size();
  }

  public void putToServicePurgestates(String key, ServicePurgeState val) {
    if (this.servicePurgestates == null) {
      this.servicePurgestates = new HashMap<String,ServicePurgeState>();
    }
    this.servicePurgestates.put(key, val);
  }

  public Map<String,ServicePurgeState> getServicePurgestates() {
    return this.servicePurgestates;
  }

  public ApplicationPurgeState setServicePurgestates(Map<String,ServicePurgeState> servicePurgestates) {
    this.servicePurgestates = servicePurgestates;
    return this;
  }

  public void unsetServicePurgestates() {
    this.servicePurgestates = null;
  }

  /** Returns true if field servicePurgestates is set (has been assigned a value) and false otherwise */
  public boolean isSetServicePurgestates() {
    return this.servicePurgestates != null;
  }

  public void setServicePurgestatesIsSet(boolean value) {
    if (!value) {
      this.servicePurgestates = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case SERVICE_PURGESTATES:
      if (value == null) {
        unsetServicePurgestates();
      } else {
        setServicePurgestates((Map<String,ServicePurgeState>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case SERVICE_PURGESTATES:
      return getServicePurgestates();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case SERVICE_PURGESTATES:
      return isSetServicePurgestates();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ApplicationPurgeState)
      return this.equals((ApplicationPurgeState)that);
    return false;
  }

  public boolean equals(ApplicationPurgeState that) {
    if (that == null)
      return false;

    boolean this_present_servicePurgestates = true && this.isSetServicePurgestates();
    boolean that_present_servicePurgestates = true && that.isSetServicePurgestates();
    if (this_present_servicePurgestates || that_present_servicePurgestates) {
      if (!(this_present_servicePurgestates && that_present_servicePurgestates))
        return false;
      if (!this.servicePurgestates.equals(that.servicePurgestates))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    HashCodeBuilder builder = new HashCodeBuilder();

    boolean present_servicePurgestates = true && (isSetServicePurgestates());
    builder.append(present_servicePurgestates);
    if (present_servicePurgestates)
      builder.append(servicePurgestates);

    return builder.toHashCode();
  }

  @Override
  public int compareTo(ApplicationPurgeState other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetServicePurgestates()).compareTo(other.isSetServicePurgestates());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetServicePurgestates()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.servicePurgestates, other.servicePurgestates);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("ApplicationPurgeState(");
    boolean first = true;

    sb.append("servicePurgestates:");
    if (this.servicePurgestates == null) {
      sb.append("null");
    } else {
      sb.append(this.servicePurgestates);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (servicePurgestates == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'servicePurgestates' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ApplicationPurgeStateStandardSchemeFactory implements SchemeFactory {
    public ApplicationPurgeStateStandardScheme getScheme() {
      return new ApplicationPurgeStateStandardScheme();
    }
  }

  private static class ApplicationPurgeStateStandardScheme extends StandardScheme<ApplicationPurgeState> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ApplicationPurgeState struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // SERVICE_PURGESTATES
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map0 = iprot.readMapBegin();
                struct.servicePurgestates = new HashMap<String,ServicePurgeState>(2*_map0.size);
                for (int _i1 = 0; _i1 < _map0.size; ++_i1)
                {
                  String _key2;
                  ServicePurgeState _val3;
                  _key2 = iprot.readString();
                  _val3 = new ServicePurgeState();
                  _val3.read(iprot);
                  struct.servicePurgestates.put(_key2, _val3);
                }
                iprot.readMapEnd();
              }
              struct.setServicePurgestatesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ApplicationPurgeState struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.servicePurgestates != null) {
        oprot.writeFieldBegin(SERVICE_PURGESTATES_FIELD_DESC);
        {
          oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRUCT, struct.servicePurgestates.size()));
          for (Map.Entry<String, ServicePurgeState> _iter4 : struct.servicePurgestates.entrySet())
          {
            oprot.writeString(_iter4.getKey());
            _iter4.getValue().write(oprot);
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ApplicationPurgeStateTupleSchemeFactory implements SchemeFactory {
    public ApplicationPurgeStateTupleScheme getScheme() {
      return new ApplicationPurgeStateTupleScheme();
    }
  }

  private static class ApplicationPurgeStateTupleScheme extends TupleScheme<ApplicationPurgeState> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ApplicationPurgeState struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      {
        oprot.writeI32(struct.servicePurgestates.size());
        for (Map.Entry<String, ServicePurgeState> _iter5 : struct.servicePurgestates.entrySet())
        {
          oprot.writeString(_iter5.getKey());
          _iter5.getValue().write(oprot);
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ApplicationPurgeState struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      {
        org.apache.thrift.protocol.TMap _map6 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
        struct.servicePurgestates = new HashMap<String,ServicePurgeState>(2*_map6.size);
        for (int _i7 = 0; _i7 < _map6.size; ++_i7)
        {
          String _key8;
          ServicePurgeState _val9;
          _key8 = iprot.readString();
          _val9 = new ServicePurgeState();
          _val9.read(iprot);
          struct.servicePurgestates.put(_key8, _val9);
        }
      }
      struct.setServicePurgestatesIsSet(true);
    }
  }

}

