/*   Copyright (C) 2013-2014 Computer Sciences Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License. */

/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ezbake.services.centralPurge.thrift;

import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class CentralAgeOffEventQueryResults implements org.apache.thrift.TBase<CentralAgeOffEventQueryResults, CentralAgeOffEventQueryResults._Fields>, java.io.Serializable, Cloneable, Comparable<CentralAgeOffEventQueryResults> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("CentralAgeOffEventQueryResults");

  private static final org.apache.thrift.protocol.TField AGE_OFF_EVENT_STATES_FIELD_DESC = new org.apache.thrift.protocol.TField("ageOffEventStates", org.apache.thrift.protocol.TType.LIST, (short)1);
  private static final org.apache.thrift.protocol.TField COUNT_FIELD_DESC = new org.apache.thrift.protocol.TField("count", org.apache.thrift.protocol.TType.I64, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new CentralAgeOffEventQueryResultsStandardSchemeFactory());
    schemes.put(TupleScheme.class, new CentralAgeOffEventQueryResultsTupleSchemeFactory());
  }

  public List<CentralAgeOffEventState> ageOffEventStates; // required
  public long count; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    AGE_OFF_EVENT_STATES((short)1, "ageOffEventStates"),
    COUNT((short)2, "count");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // AGE_OFF_EVENT_STATES
          return AGE_OFF_EVENT_STATES;
        case 2: // COUNT
          return COUNT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __COUNT_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.AGE_OFF_EVENT_STATES, new org.apache.thrift.meta_data.FieldMetaData("ageOffEventStates", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, CentralAgeOffEventState.class))));
    tmpMap.put(_Fields.COUNT, new org.apache.thrift.meta_data.FieldMetaData("count", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(CentralAgeOffEventQueryResults.class, metaDataMap);
  }

  public CentralAgeOffEventQueryResults() {
  }

  public CentralAgeOffEventQueryResults(
    List<CentralAgeOffEventState> ageOffEventStates,
    long count)
  {
    this();
    this.ageOffEventStates = ageOffEventStates;
    this.count = count;
    setCountIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public CentralAgeOffEventQueryResults(CentralAgeOffEventQueryResults other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetAgeOffEventStates()) {
      List<CentralAgeOffEventState> __this__ageOffEventStates = new ArrayList<CentralAgeOffEventState>(other.ageOffEventStates.size());
      for (CentralAgeOffEventState other_element : other.ageOffEventStates) {
        __this__ageOffEventStates.add(new CentralAgeOffEventState(other_element));
      }
      this.ageOffEventStates = __this__ageOffEventStates;
    }
    this.count = other.count;
  }

  public CentralAgeOffEventQueryResults deepCopy() {
    return new CentralAgeOffEventQueryResults(this);
  }

  @Override
  public void clear() {
    this.ageOffEventStates = null;
    setCountIsSet(false);
    this.count = 0;
  }

  public int getAgeOffEventStatesSize() {
    return (this.ageOffEventStates == null) ? 0 : this.ageOffEventStates.size();
  }

  public java.util.Iterator<CentralAgeOffEventState> getAgeOffEventStatesIterator() {
    return (this.ageOffEventStates == null) ? null : this.ageOffEventStates.iterator();
  }

  public void addToAgeOffEventStates(CentralAgeOffEventState elem) {
    if (this.ageOffEventStates == null) {
      this.ageOffEventStates = new ArrayList<CentralAgeOffEventState>();
    }
    this.ageOffEventStates.add(elem);
  }

  public List<CentralAgeOffEventState> getAgeOffEventStates() {
    return this.ageOffEventStates;
  }

  public CentralAgeOffEventQueryResults setAgeOffEventStates(List<CentralAgeOffEventState> ageOffEventStates) {
    this.ageOffEventStates = ageOffEventStates;
    return this;
  }

  public void unsetAgeOffEventStates() {
    this.ageOffEventStates = null;
  }

  /** Returns true if field ageOffEventStates is set (has been assigned a value) and false otherwise */
  public boolean isSetAgeOffEventStates() {
    return this.ageOffEventStates != null;
  }

  public void setAgeOffEventStatesIsSet(boolean value) {
    if (!value) {
      this.ageOffEventStates = null;
    }
  }

  public long getCount() {
    return this.count;
  }

  public CentralAgeOffEventQueryResults setCount(long count) {
    this.count = count;
    setCountIsSet(true);
    return this;
  }

  public void unsetCount() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __COUNT_ISSET_ID);
  }

  /** Returns true if field count is set (has been assigned a value) and false otherwise */
  public boolean isSetCount() {
    return EncodingUtils.testBit(__isset_bitfield, __COUNT_ISSET_ID);
  }

  public void setCountIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __COUNT_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case AGE_OFF_EVENT_STATES:
      if (value == null) {
        unsetAgeOffEventStates();
      } else {
        setAgeOffEventStates((List<CentralAgeOffEventState>)value);
      }
      break;

    case COUNT:
      if (value == null) {
        unsetCount();
      } else {
        setCount((Long)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case AGE_OFF_EVENT_STATES:
      return getAgeOffEventStates();

    case COUNT:
      return Long.valueOf(getCount());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case AGE_OFF_EVENT_STATES:
      return isSetAgeOffEventStates();
    case COUNT:
      return isSetCount();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof CentralAgeOffEventQueryResults)
      return this.equals((CentralAgeOffEventQueryResults)that);
    return false;
  }

  public boolean equals(CentralAgeOffEventQueryResults that) {
    if (that == null)
      return false;

    boolean this_present_ageOffEventStates = true && this.isSetAgeOffEventStates();
    boolean that_present_ageOffEventStates = true && that.isSetAgeOffEventStates();
    if (this_present_ageOffEventStates || that_present_ageOffEventStates) {
      if (!(this_present_ageOffEventStates && that_present_ageOffEventStates))
        return false;
      if (!this.ageOffEventStates.equals(that.ageOffEventStates))
        return false;
    }

    boolean this_present_count = true;
    boolean that_present_count = true;
    if (this_present_count || that_present_count) {
      if (!(this_present_count && that_present_count))
        return false;
      if (this.count != that.count)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    HashCodeBuilder builder = new HashCodeBuilder();

    boolean present_ageOffEventStates = true && (isSetAgeOffEventStates());
    builder.append(present_ageOffEventStates);
    if (present_ageOffEventStates)
      builder.append(ageOffEventStates);

    boolean present_count = true;
    builder.append(present_count);
    if (present_count)
      builder.append(count);

    return builder.toHashCode();
  }

  @Override
  public int compareTo(CentralAgeOffEventQueryResults other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetAgeOffEventStates()).compareTo(other.isSetAgeOffEventStates());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAgeOffEventStates()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ageOffEventStates, other.ageOffEventStates);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCount()).compareTo(other.isSetCount());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCount()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.count, other.count);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("CentralAgeOffEventQueryResults(");
    boolean first = true;

    sb.append("ageOffEventStates:");
    if (this.ageOffEventStates == null) {
      sb.append("null");
    } else {
      sb.append(this.ageOffEventStates);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("count:");
    sb.append(this.count);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (ageOffEventStates == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'ageOffEventStates' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'count' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class CentralAgeOffEventQueryResultsStandardSchemeFactory implements SchemeFactory {
    public CentralAgeOffEventQueryResultsStandardScheme getScheme() {
      return new CentralAgeOffEventQueryResultsStandardScheme();
    }
  }

  private static class CentralAgeOffEventQueryResultsStandardScheme extends StandardScheme<CentralAgeOffEventQueryResults> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, CentralAgeOffEventQueryResults struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // AGE_OFF_EVENT_STATES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list54 = iprot.readListBegin();
                struct.ageOffEventStates = new ArrayList<CentralAgeOffEventState>(_list54.size);
                for (int _i55 = 0; _i55 < _list54.size; ++_i55)
                {
                  CentralAgeOffEventState _elem56;
                  _elem56 = new CentralAgeOffEventState();
                  _elem56.read(iprot);
                  struct.ageOffEventStates.add(_elem56);
                }
                iprot.readListEnd();
              }
              struct.setAgeOffEventStatesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // COUNT
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.count = iprot.readI64();
              struct.setCountIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetCount()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'count' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, CentralAgeOffEventQueryResults struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.ageOffEventStates != null) {
        oprot.writeFieldBegin(AGE_OFF_EVENT_STATES_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.ageOffEventStates.size()));
          for (CentralAgeOffEventState _iter57 : struct.ageOffEventStates)
          {
            _iter57.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(COUNT_FIELD_DESC);
      oprot.writeI64(struct.count);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class CentralAgeOffEventQueryResultsTupleSchemeFactory implements SchemeFactory {
    public CentralAgeOffEventQueryResultsTupleScheme getScheme() {
      return new CentralAgeOffEventQueryResultsTupleScheme();
    }
  }

  private static class CentralAgeOffEventQueryResultsTupleScheme extends TupleScheme<CentralAgeOffEventQueryResults> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, CentralAgeOffEventQueryResults struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      {
        oprot.writeI32(struct.ageOffEventStates.size());
        for (CentralAgeOffEventState _iter58 : struct.ageOffEventStates)
        {
          _iter58.write(oprot);
        }
      }
      oprot.writeI64(struct.count);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, CentralAgeOffEventQueryResults struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      {
        org.apache.thrift.protocol.TList _list59 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
        struct.ageOffEventStates = new ArrayList<CentralAgeOffEventState>(_list59.size);
        for (int _i60 = 0; _i60 < _list59.size; ++_i60)
        {
          CentralAgeOffEventState _elem61;
          _elem61 = new CentralAgeOffEventState();
          _elem61.read(iprot);
          struct.ageOffEventStates.add(_elem61);
        }
      }
      struct.setAgeOffEventStatesIsSet(true);
      struct.count = iprot.readI64();
      struct.setCountIsSet(true);
    }
  }

}

