/*   Copyright (C) 2013-2014 Computer Sciences Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License. */

/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ezbake.services.centralPurge.thrift;

import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class CentralPurgeState implements org.apache.thrift.TBase<CentralPurgeState, CentralPurgeState._Fields>, java.io.Serializable, Cloneable, Comparable<CentralPurgeState> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("CentralPurgeState");

  private static final org.apache.thrift.protocol.TField APPLICATION_STATES_FIELD_DESC = new org.apache.thrift.protocol.TField("applicationStates", org.apache.thrift.protocol.TType.MAP, (short)1);
  private static final org.apache.thrift.protocol.TField PURGE_INFO_FIELD_DESC = new org.apache.thrift.protocol.TField("purgeInfo", org.apache.thrift.protocol.TType.STRUCT, (short)2);
  private static final org.apache.thrift.protocol.TField CENTRAL_STATUS_FIELD_DESC = new org.apache.thrift.protocol.TField("centralStatus", org.apache.thrift.protocol.TType.I32, (short)3);
  private static final org.apache.thrift.protocol.TField CENTRAL_PURGE_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("centralPurgeType", org.apache.thrift.protocol.TType.I32, (short)4);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new CentralPurgeStateStandardSchemeFactory());
    schemes.put(TupleScheme.class, new CentralPurgeStateTupleSchemeFactory());
  }

  public Map<String,ApplicationPurgeState> applicationStates; // required
  public ezbake.services.provenance.thrift.PurgeInfo purgeInfo; // required
  /**
   * 
   * @see CentralPurgeStatus
   */
  public CentralPurgeStatus centralStatus; // required
  /**
   * 
   * @see CentralPurgeType
   */
  public CentralPurgeType centralPurgeType; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    APPLICATION_STATES((short)1, "applicationStates"),
    PURGE_INFO((short)2, "purgeInfo"),
    /**
     * 
     * @see CentralPurgeStatus
     */
    CENTRAL_STATUS((short)3, "centralStatus"),
    /**
     * 
     * @see CentralPurgeType
     */
    CENTRAL_PURGE_TYPE((short)4, "centralPurgeType");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // APPLICATION_STATES
          return APPLICATION_STATES;
        case 2: // PURGE_INFO
          return PURGE_INFO;
        case 3: // CENTRAL_STATUS
          return CENTRAL_STATUS;
        case 4: // CENTRAL_PURGE_TYPE
          return CENTRAL_PURGE_TYPE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.APPLICATION_STATES, new org.apache.thrift.meta_data.FieldMetaData("applicationStates", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ApplicationPurgeState.class))));
    tmpMap.put(_Fields.PURGE_INFO, new org.apache.thrift.meta_data.FieldMetaData("purgeInfo", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ezbake.services.provenance.thrift.PurgeInfo.class)));
    tmpMap.put(_Fields.CENTRAL_STATUS, new org.apache.thrift.meta_data.FieldMetaData("centralStatus", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, CentralPurgeStatus.class)));
    tmpMap.put(_Fields.CENTRAL_PURGE_TYPE, new org.apache.thrift.meta_data.FieldMetaData("centralPurgeType", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, CentralPurgeType.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(CentralPurgeState.class, metaDataMap);
  }

  public CentralPurgeState() {
  }

  public CentralPurgeState(
    Map<String,ApplicationPurgeState> applicationStates,
    ezbake.services.provenance.thrift.PurgeInfo purgeInfo,
    CentralPurgeStatus centralStatus,
    CentralPurgeType centralPurgeType)
  {
    this();
    this.applicationStates = applicationStates;
    this.purgeInfo = purgeInfo;
    this.centralStatus = centralStatus;
    this.centralPurgeType = centralPurgeType;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public CentralPurgeState(CentralPurgeState other) {
    if (other.isSetApplicationStates()) {
      Map<String,ApplicationPurgeState> __this__applicationStates = new HashMap<String,ApplicationPurgeState>(other.applicationStates.size());
      for (Map.Entry<String, ApplicationPurgeState> other_element : other.applicationStates.entrySet()) {

        String other_element_key = other_element.getKey();
        ApplicationPurgeState other_element_value = other_element.getValue();

        String __this__applicationStates_copy_key = other_element_key;

        ApplicationPurgeState __this__applicationStates_copy_value = new ApplicationPurgeState(other_element_value);

        __this__applicationStates.put(__this__applicationStates_copy_key, __this__applicationStates_copy_value);
      }
      this.applicationStates = __this__applicationStates;
    }
    if (other.isSetPurgeInfo()) {
      this.purgeInfo = new ezbake.services.provenance.thrift.PurgeInfo(other.purgeInfo);
    }
    if (other.isSetCentralStatus()) {
      this.centralStatus = other.centralStatus;
    }
    if (other.isSetCentralPurgeType()) {
      this.centralPurgeType = other.centralPurgeType;
    }
  }

  public CentralPurgeState deepCopy() {
    return new CentralPurgeState(this);
  }

  @Override
  public void clear() {
    this.applicationStates = null;
    this.purgeInfo = null;
    this.centralStatus = null;
    this.centralPurgeType = null;
  }

  public int getApplicationStatesSize() {
    return (this.applicationStates == null) ? 0 : this.applicationStates.size();
  }

  public void putToApplicationStates(String key, ApplicationPurgeState val) {
    if (this.applicationStates == null) {
      this.applicationStates = new HashMap<String,ApplicationPurgeState>();
    }
    this.applicationStates.put(key, val);
  }

  public Map<String,ApplicationPurgeState> getApplicationStates() {
    return this.applicationStates;
  }

  public CentralPurgeState setApplicationStates(Map<String,ApplicationPurgeState> applicationStates) {
    this.applicationStates = applicationStates;
    return this;
  }

  public void unsetApplicationStates() {
    this.applicationStates = null;
  }

  /** Returns true if field applicationStates is set (has been assigned a value) and false otherwise */
  public boolean isSetApplicationStates() {
    return this.applicationStates != null;
  }

  public void setApplicationStatesIsSet(boolean value) {
    if (!value) {
      this.applicationStates = null;
    }
  }

  public ezbake.services.provenance.thrift.PurgeInfo getPurgeInfo() {
    return this.purgeInfo;
  }

  public CentralPurgeState setPurgeInfo(ezbake.services.provenance.thrift.PurgeInfo purgeInfo) {
    this.purgeInfo = purgeInfo;
    return this;
  }

  public void unsetPurgeInfo() {
    this.purgeInfo = null;
  }

  /** Returns true if field purgeInfo is set (has been assigned a value) and false otherwise */
  public boolean isSetPurgeInfo() {
    return this.purgeInfo != null;
  }

  public void setPurgeInfoIsSet(boolean value) {
    if (!value) {
      this.purgeInfo = null;
    }
  }

  /**
   * 
   * @see CentralPurgeStatus
   */
  public CentralPurgeStatus getCentralStatus() {
    return this.centralStatus;
  }

  /**
   * 
   * @see CentralPurgeStatus
   */
  public CentralPurgeState setCentralStatus(CentralPurgeStatus centralStatus) {
    this.centralStatus = centralStatus;
    return this;
  }

  public void unsetCentralStatus() {
    this.centralStatus = null;
  }

  /** Returns true if field centralStatus is set (has been assigned a value) and false otherwise */
  public boolean isSetCentralStatus() {
    return this.centralStatus != null;
  }

  public void setCentralStatusIsSet(boolean value) {
    if (!value) {
      this.centralStatus = null;
    }
  }

  /**
   * 
   * @see CentralPurgeType
   */
  public CentralPurgeType getCentralPurgeType() {
    return this.centralPurgeType;
  }

  /**
   * 
   * @see CentralPurgeType
   */
  public CentralPurgeState setCentralPurgeType(CentralPurgeType centralPurgeType) {
    this.centralPurgeType = centralPurgeType;
    return this;
  }

  public void unsetCentralPurgeType() {
    this.centralPurgeType = null;
  }

  /** Returns true if field centralPurgeType is set (has been assigned a value) and false otherwise */
  public boolean isSetCentralPurgeType() {
    return this.centralPurgeType != null;
  }

  public void setCentralPurgeTypeIsSet(boolean value) {
    if (!value) {
      this.centralPurgeType = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case APPLICATION_STATES:
      if (value == null) {
        unsetApplicationStates();
      } else {
        setApplicationStates((Map<String,ApplicationPurgeState>)value);
      }
      break;

    case PURGE_INFO:
      if (value == null) {
        unsetPurgeInfo();
      } else {
        setPurgeInfo((ezbake.services.provenance.thrift.PurgeInfo)value);
      }
      break;

    case CENTRAL_STATUS:
      if (value == null) {
        unsetCentralStatus();
      } else {
        setCentralStatus((CentralPurgeStatus)value);
      }
      break;

    case CENTRAL_PURGE_TYPE:
      if (value == null) {
        unsetCentralPurgeType();
      } else {
        setCentralPurgeType((CentralPurgeType)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case APPLICATION_STATES:
      return getApplicationStates();

    case PURGE_INFO:
      return getPurgeInfo();

    case CENTRAL_STATUS:
      return getCentralStatus();

    case CENTRAL_PURGE_TYPE:
      return getCentralPurgeType();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case APPLICATION_STATES:
      return isSetApplicationStates();
    case PURGE_INFO:
      return isSetPurgeInfo();
    case CENTRAL_STATUS:
      return isSetCentralStatus();
    case CENTRAL_PURGE_TYPE:
      return isSetCentralPurgeType();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof CentralPurgeState)
      return this.equals((CentralPurgeState)that);
    return false;
  }

  public boolean equals(CentralPurgeState that) {
    if (that == null)
      return false;

    boolean this_present_applicationStates = true && this.isSetApplicationStates();
    boolean that_present_applicationStates = true && that.isSetApplicationStates();
    if (this_present_applicationStates || that_present_applicationStates) {
      if (!(this_present_applicationStates && that_present_applicationStates))
        return false;
      if (!this.applicationStates.equals(that.applicationStates))
        return false;
    }

    boolean this_present_purgeInfo = true && this.isSetPurgeInfo();
    boolean that_present_purgeInfo = true && that.isSetPurgeInfo();
    if (this_present_purgeInfo || that_present_purgeInfo) {
      if (!(this_present_purgeInfo && that_present_purgeInfo))
        return false;
      if (!this.purgeInfo.equals(that.purgeInfo))
        return false;
    }

    boolean this_present_centralStatus = true && this.isSetCentralStatus();
    boolean that_present_centralStatus = true && that.isSetCentralStatus();
    if (this_present_centralStatus || that_present_centralStatus) {
      if (!(this_present_centralStatus && that_present_centralStatus))
        return false;
      if (!this.centralStatus.equals(that.centralStatus))
        return false;
    }

    boolean this_present_centralPurgeType = true && this.isSetCentralPurgeType();
    boolean that_present_centralPurgeType = true && that.isSetCentralPurgeType();
    if (this_present_centralPurgeType || that_present_centralPurgeType) {
      if (!(this_present_centralPurgeType && that_present_centralPurgeType))
        return false;
      if (!this.centralPurgeType.equals(that.centralPurgeType))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    HashCodeBuilder builder = new HashCodeBuilder();

    boolean present_applicationStates = true && (isSetApplicationStates());
    builder.append(present_applicationStates);
    if (present_applicationStates)
      builder.append(applicationStates);

    boolean present_purgeInfo = true && (isSetPurgeInfo());
    builder.append(present_purgeInfo);
    if (present_purgeInfo)
      builder.append(purgeInfo);

    boolean present_centralStatus = true && (isSetCentralStatus());
    builder.append(present_centralStatus);
    if (present_centralStatus)
      builder.append(centralStatus.getValue());

    boolean present_centralPurgeType = true && (isSetCentralPurgeType());
    builder.append(present_centralPurgeType);
    if (present_centralPurgeType)
      builder.append(centralPurgeType.getValue());

    return builder.toHashCode();
  }

  @Override
  public int compareTo(CentralPurgeState other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetApplicationStates()).compareTo(other.isSetApplicationStates());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetApplicationStates()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.applicationStates, other.applicationStates);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPurgeInfo()).compareTo(other.isSetPurgeInfo());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPurgeInfo()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.purgeInfo, other.purgeInfo);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCentralStatus()).compareTo(other.isSetCentralStatus());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCentralStatus()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.centralStatus, other.centralStatus);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCentralPurgeType()).compareTo(other.isSetCentralPurgeType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCentralPurgeType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.centralPurgeType, other.centralPurgeType);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("CentralPurgeState(");
    boolean first = true;

    sb.append("applicationStates:");
    if (this.applicationStates == null) {
      sb.append("null");
    } else {
      sb.append(this.applicationStates);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("purgeInfo:");
    if (this.purgeInfo == null) {
      sb.append("null");
    } else {
      sb.append(this.purgeInfo);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("centralStatus:");
    if (this.centralStatus == null) {
      sb.append("null");
    } else {
      sb.append(this.centralStatus);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("centralPurgeType:");
    if (this.centralPurgeType == null) {
      sb.append("null");
    } else {
      sb.append(this.centralPurgeType);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (applicationStates == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'applicationStates' was not present! Struct: " + toString());
    }
    if (purgeInfo == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'purgeInfo' was not present! Struct: " + toString());
    }
    if (centralStatus == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'centralStatus' was not present! Struct: " + toString());
    }
    if (centralPurgeType == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'centralPurgeType' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
    if (purgeInfo != null) {
      purgeInfo.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class CentralPurgeStateStandardSchemeFactory implements SchemeFactory {
    public CentralPurgeStateStandardScheme getScheme() {
      return new CentralPurgeStateStandardScheme();
    }
  }

  private static class CentralPurgeStateStandardScheme extends StandardScheme<CentralPurgeState> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, CentralPurgeState struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // APPLICATION_STATES
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map10 = iprot.readMapBegin();
                struct.applicationStates = new HashMap<String,ApplicationPurgeState>(2*_map10.size);
                for (int _i11 = 0; _i11 < _map10.size; ++_i11)
                {
                  String _key12;
                  ApplicationPurgeState _val13;
                  _key12 = iprot.readString();
                  _val13 = new ApplicationPurgeState();
                  _val13.read(iprot);
                  struct.applicationStates.put(_key12, _val13);
                }
                iprot.readMapEnd();
              }
              struct.setApplicationStatesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PURGE_INFO
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.purgeInfo = new ezbake.services.provenance.thrift.PurgeInfo();
              struct.purgeInfo.read(iprot);
              struct.setPurgeInfoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // CENTRAL_STATUS
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.centralStatus = CentralPurgeStatus.findByValue(iprot.readI32());
              struct.setCentralStatusIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // CENTRAL_PURGE_TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.centralPurgeType = CentralPurgeType.findByValue(iprot.readI32());
              struct.setCentralPurgeTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, CentralPurgeState struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.applicationStates != null) {
        oprot.writeFieldBegin(APPLICATION_STATES_FIELD_DESC);
        {
          oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRUCT, struct.applicationStates.size()));
          for (Map.Entry<String, ApplicationPurgeState> _iter14 : struct.applicationStates.entrySet())
          {
            oprot.writeString(_iter14.getKey());
            _iter14.getValue().write(oprot);
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.purgeInfo != null) {
        oprot.writeFieldBegin(PURGE_INFO_FIELD_DESC);
        struct.purgeInfo.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.centralStatus != null) {
        oprot.writeFieldBegin(CENTRAL_STATUS_FIELD_DESC);
        oprot.writeI32(struct.centralStatus.getValue());
        oprot.writeFieldEnd();
      }
      if (struct.centralPurgeType != null) {
        oprot.writeFieldBegin(CENTRAL_PURGE_TYPE_FIELD_DESC);
        oprot.writeI32(struct.centralPurgeType.getValue());
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class CentralPurgeStateTupleSchemeFactory implements SchemeFactory {
    public CentralPurgeStateTupleScheme getScheme() {
      return new CentralPurgeStateTupleScheme();
    }
  }

  private static class CentralPurgeStateTupleScheme extends TupleScheme<CentralPurgeState> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, CentralPurgeState struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      {
        oprot.writeI32(struct.applicationStates.size());
        for (Map.Entry<String, ApplicationPurgeState> _iter15 : struct.applicationStates.entrySet())
        {
          oprot.writeString(_iter15.getKey());
          _iter15.getValue().write(oprot);
        }
      }
      struct.purgeInfo.write(oprot);
      oprot.writeI32(struct.centralStatus.getValue());
      oprot.writeI32(struct.centralPurgeType.getValue());
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, CentralPurgeState struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      {
        org.apache.thrift.protocol.TMap _map16 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
        struct.applicationStates = new HashMap<String,ApplicationPurgeState>(2*_map16.size);
        for (int _i17 = 0; _i17 < _map16.size; ++_i17)
        {
          String _key18;
          ApplicationPurgeState _val19;
          _key18 = iprot.readString();
          _val19 = new ApplicationPurgeState();
          _val19.read(iprot);
          struct.applicationStates.put(_key18, _val19);
        }
      }
      struct.setApplicationStatesIsSet(true);
      struct.purgeInfo = new ezbake.services.provenance.thrift.PurgeInfo();
      struct.purgeInfo.read(iprot);
      struct.setPurgeInfoIsSet(true);
      struct.centralStatus = CentralPurgeStatus.findByValue(iprot.readI32());
      struct.setCentralStatusIsSet(true);
      struct.centralPurgeType = CentralPurgeType.findByValue(iprot.readI32());
      struct.setCentralPurgeTypeIsSet(true);
    }
  }

}

