/*   Copyright (C) 2013-2014 Computer Sciences Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License. */

/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ezbake.services.centralPurge.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum CentralPurgeStatus implements org.apache.thrift.TEnum {
  ACTIVE(0),
  ACTIVE_MANUAL_INTERVENTION_WILL_BE_NEEDED(1),
  STOPPED_MANUAL_INTERVENTION_NEEDED(2),
  RESOLVED_AUTOMATICALLY(3),
  RESOLVED_MANUALLY(4);

  private final int value;

  private CentralPurgeStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static CentralPurgeStatus findByValue(int value) { 
    switch (value) {
      case 0:
        return ACTIVE;
      case 1:
        return ACTIVE_MANUAL_INTERVENTION_WILL_BE_NEEDED;
      case 2:
        return STOPPED_MANUAL_INTERVENTION_NEEDED;
      case 3:
        return RESOLVED_AUTOMATICALLY;
      case 4:
        return RESOLVED_MANUALLY;
      default:
        return null;
    }
  }
}
